import { Linking, Pressable, ScrollView, Text, View, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import { MOCK_SAFETY_RESOURCES } from '@/data/mockData';
import { colors, darkColors } from '@/constants/colors';
import { useTheme } from '@/context/ThemeProvider';
export default function Safety() { const router = useRouter(); const { isDark } = useTheme(); return <SafeAreaView style={[styles.safe, isDark && styles.safeDark]}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => (router.canGoBack() ? router.back() : router.replace('/'))}><Text style={[styles.back, isDark && styles.darkText]}>{'‹'}  Safety & Support</Text></Pressable><Text style={[styles.subtitle, isDark && styles.darkSecondaryText]}>Resources and support for the LGBTQIA+ community in and around Sandton.</Text><Button label="🚨 Emergency SOS · Call 112" variant="danger" onPress={() => Linking.openURL('tel:112')} /><View style={styles.gap} />{MOCK_SAFETY_RESOURCES.map((resource) => <Card key={resource.id} style={styles.resource}><Text style={styles.type}>{resource.resourceType.replace('_', ' ')}</Text><Text style={[styles.resourceTitle, isDark && styles.darkText]}>{resource.title}</Text><Text style={[styles.copy, isDark && styles.darkSecondaryText]}>{resource.description}</Text>{resource.phoneContact && <Button label={`Call ${resource.phoneContact}`} onPress={() => Linking.openURL(`tel:${resource.phoneContact}`)} />}{resource.websiteUrl && <Button label="Visit website" variant="secondary" style={styles.websiteButton} onPress={() => Linking.openURL(resource.websiteUrl!)} />}</Card>)}<LinearGradient colors={[colors.primary, colors.gradientEnd]} style={styles.route}><Text style={styles.routeTitle}>Pink Route Safe Walk • Sandton</Text><Text style={styles.routeCopy}>Share your route with a trusted contact while you travel through Sandon and nearby areas.</Text><Button label="Start a safe walk" variant="secondary" onPress={() => router.replace('/(tabs)/route')} /></LinearGradient></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: 'transparent' }, safeDark: { backgroundColor: 'transparent' }, darkText: { color: darkColors.textPrimary }, darkSecondaryText: { color: darkColors.textSecondary }, content: { padding: 20, paddingBottom: 120 }, back: { color: colors.textPrimary, fontSize: 24, fontWeight: '600', marginBottom: 4 }, subtitle: { color: colors.textSecondary, fontSize: 14, marginBottom: 20 }, gap: { height: 16 }, resource: { marginBottom: 12 }, websiteButton: { marginTop: 10 }, type: { color: colors.primary, fontSize: 10, fontWeight: '600', textTransform: 'uppercase', marginBottom: 6 }, resourceTitle: { color: colors.textPrimary, fontSize: 16, fontWeight: '600' }, copy: { color: colors.textSecondary, fontSize: 13, lineHeight: 20, marginVertical: 10 }, route: { borderRadius: 24, padding: 20, marginTop: 8 }, routeTitle: { color: '#fff', fontSize: 18, fontWeight: '600' }, routeCopy: { color: '#F5E8FF', lineHeight: 20, marginVertical: 10 } });

