import { useEffect, useMemo, useRef } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import WebView from 'react-native-webview';
import type { Place } from '@/types';

type RouteMapProps = {
  places: Place[]; selectedPlace: Place | null; dark: boolean;
  onDarkChange: (dark: boolean) => void; onSelectPlace: (place: Place) => void;
  onClosePlace: () => void; onOpenPlace: (place: Place) => void;
  onAddPlace: (place: Place) => void; onSharePlace: (place: Place) => void;
  onCheckIn: (place: Place) => void; routeProgress: number;
};

export default function RouteMap({ places, selectedPlace, dark, onDarkChange, onSelectPlace, onClosePlace, onOpenPlace, onAddPlace, onSharePlace, onCheckIn, routeProgress }: RouteMapProps) {
  const webViewRef = useRef<WebView>(null);
  const mapHtml = useMemo(() => {
    const markers = places.map((place, index) => {
      const label = index === 0 ? 'FROM' : index === places.length - 1 ? 'TO' : 'VIA';
      return `const marker${place.id}=L.marker([${place.coords.latitude},${place.coords.longitude}],{icon:L.divIcon({className:'pink-route-marker-shell',html:'<span class="pink-route-marker">${label}</span>',iconSize:[56,28],iconAnchor:[28,14]})}).addTo(map);marker${place.id}.on('click',()=>window.ReactNativeWebView.postMessage(JSON.stringify({action:'select',placeId:'${place.id}'})));`;
    }).join('');
    return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/><style>html,body,#map{margin:0;height:100%;width:100%;background:${dark ? '#17212B' : '#F3F6F7'}}#map{border-radius:22px}.pink-route-marker-shell{background:transparent;border:0}.pink-route-marker{display:inline-flex;align-items:center;justify-content:center;min-width:56px;height:28px;border-radius:999px;background:#EC4899;color:#fff;border:2px solid #fff;font-size:9px;font-weight:700}</style></head><body><div id="map"></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const map=L.map('map',{zoomControl:false,attributionControl:false}).setView(${selectedPlace ? `[${selectedPlace.coords.latitude},${selectedPlace.coords.longitude}]` : '[-26.1952,28.0341]'},${selectedPlace ? 15 : 13});L.tileLayer(${JSON.stringify(dark ? 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png' : 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png')},{subdomains:'abcd',maxZoom:20}).addTo(map);const route=[[-26.2041,28.0473],[-26.1907,28.0325],${places.map(() => '[-26.1952,28.0341]').join(',')},[-26.1854,28.0242]];L.polyline(route,{color:'#7C3AED',weight:11,opacity:.24}).addTo(map);let passed,remaining,you;window.updateMockPosition=p=>{const s=Math.min(Math.max(p,0),1)*(route.length-1),i=Math.min(Math.floor(s),route.length-2),f=s-i,point=[route[i][0]+(route[i+1][0]-route[i][0])*f,route[i][1]+(route[i+1][1]-route[i][1])*f];passed?.remove();remaining?.remove();you?.remove();passed=L.polyline(route.slice(0,i+1).concat([point]),{color:'#22C55E',weight:6}).addTo(map);remaining=L.polyline([point].concat(route.slice(i+1)),{color:'${dark ? '#F43F5E' : '#EC4899'}',weight:5,dashArray:'8 8'}).addTo(map);you=L.circleMarker(point,{radius:9,color:'#fff',weight:3,fillColor:'#22C55E',fillOpacity:1}).addTo(map)};window.updateMockPosition(0);${markers}</script></body></html>`;
  }, [dark, places, selectedPlace]);

  useEffect(() => { webViewRef.current?.injectJavaScript(`window.updateMockPosition?.(${routeProgress});true;`); }, [routeProgress]);
  const handleMessage = (event: { nativeEvent: { data: string } }) => { try { const payload = JSON.parse(event.nativeEvent.data); const place = places.find((item) => item.id === payload.placeId); if (place && payload.action === 'select') onSelectPlace(place); } catch { /* ignore */ } };

  return <View style={[styles.panel, dark && styles.panelDark]}><View style={styles.header}><Text style={[styles.title, dark && styles.textDark]}>Johannesburg</Text><Pressable style={styles.modeButton} onPress={() => onDarkChange(!dark)}><Text style={styles.modeText}>{dark ? 'Light' : 'Dark'}</Text></Pressable></View><View style={[styles.surface, dark && styles.surfaceDark]}><WebView ref={webViewRef} originWhitelist={['*']} source={{ html: mapHtml }} javaScriptEnabled domStorageEnabled startInLoadingState style={styles.mapView} onMessage={handleMessage}/>{selectedPlace && <View style={styles.popup}><View style={styles.popupHeader}><View style={styles.popupInfo}><Text style={styles.popupTitle}>{selectedPlace.name}</Text><Text style={styles.popupMeta}>{selectedPlace.category} • {selectedPlace.distance} • {selectedPlace.safetyScore}% safe</Text></View><Pressable onPress={onClosePlace}><Text style={styles.close}>Close</Text></Pressable></View><View style={styles.actions}><Pressable style={styles.action} onPress={() => onAddPlace(selectedPlace)}><Text style={styles.actionText}>Add to Route</Text></Pressable><Pressable style={styles.action} onPress={() => onOpenPlace(selectedPlace)}><Text style={styles.actionText}>Open</Text></Pressable><Pressable style={styles.action} onPress={() => onSharePlace(selectedPlace)}><Text style={styles.actionText}>Share</Text></Pressable></View><View style={styles.actionsSecondary}><Pressable style={styles.actionPrimary} onPress={() => onCheckIn(selectedPlace)}><Text style={styles.actionPrimaryText}>Check in</Text></Pressable></View></View>}<View style={styles.routeSummary}><Text style={styles.routeTitle}>Maboneng → Braamfontein</Text><Text style={styles.routeMeta}>12 min • 1.1 km • Safe route</Text></View></View></View>;
}

const styles = StyleSheet.create({
  panel: { borderRadius: 28, padding: 18, marginBottom: 20, borderWidth: 1, borderColor: '#DCE8F2', backgroundColor: '#F7F7F5' }, panelDark: { borderColor: '#324B63', backgroundColor: '#17212B' }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }, title: { color: '#1F2B3A', fontWeight: '600', fontSize: 18 }, textDark: { color: '#E8F0FA' }, modeButton: { backgroundColor: '#fff', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 7 }, modeText: { color: '#1F2B3A', fontSize: 11, fontWeight: '700' }, surface: { position: 'relative', minHeight: 320, overflow: 'hidden', borderRadius: 22, padding: 16, backgroundColor: '#F3F6F7' }, surfaceDark: { backgroundColor: '#1B2834' }, mapView: { width: '100%', height: 320 }, popup: { position: 'absolute', left: 12, right: 12, top: 58, zIndex: 20, backgroundColor: '#fff', borderRadius: 18, padding: 14 }, popupHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 }, popupInfo: { flex: 1 }, popupTitle: { color: '#1F2B3A', fontSize: 15, fontWeight: '700' }, popupMeta: { color: '#536776', fontSize: 11, marginTop: 5 }, close: { color: '#EC4899', fontSize: 11, fontWeight: '700' }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 }, actionsSecondary: { flexDirection: 'row', marginTop: 8 }, action: { flex: 1, minWidth: 100, alignItems: 'center', paddingVertical: 9, borderRadius: 10, backgroundColor: '#F2EAFF' }, actionText: { color: '#5B3FD6', fontSize: 11, fontWeight: '700' }, actionPrimary: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: 10, backgroundColor: '#EC4899' }, actionPrimaryText: { color: '#fff', fontSize: 11, fontWeight: '700' }, routeSummary: { marginTop: 26, padding: 14, borderRadius: 16, backgroundColor: '#fff' }, routeTitle: { color: '#1F2B3A', fontSize: 13, fontWeight: '700' }, routeMeta: { color: '#536776', fontSize: 11, marginTop: 5 },
});
